# Generated by Django 5.2.1 on 2025-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
