# Generated by Django 5.2.1 on 2025-08-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0002_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
