# Generated by Django 5.2.1 on 2025-08-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abaut',
            old_name='nama',
            new_name='judul',
        ),
    ]
