# Generated by Django 5.2.1 on 2025-08-11 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0004_rename_nama_abaut_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifikat',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
