# Generated by Django 5.2.1 on 2025-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0005_sertifikat_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(upload_to='design/')),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
