# Generated by Django 5.2.1 on 2025-10-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0006_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil', models.IntegerField(max_length=100)),
            ],
        ),
    ]
