# Generated by Django 5.2.1 on 2025-10-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0007_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skil',
            new_name='bootstra',
        ),
    ]
