# Generated by Django 5.2.1 on 2025-10-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0008_rename_skil_skill_bootstra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bootstra',
            field=models.IntegerField(),
        ),
    ]
