# Generated by Django 5.2.1 on 2025-10-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0009_alter_skill_bootstra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='bootstra',
            new_name='bootstrap',
        ),
    ]
