# Generated by Django 5.2.1 on 2025-10-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0010_rename_bootstra_skill_bootstrap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
