# Generated by Django 5.2.1 on 2025-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saya', '0011_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abaut',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abaut',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
